
+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
${PRJ_COMMON_VERIFICATION_DIR}/src/clk_rst_gen.sv
${PRJ_COMMON_VERIFICATION_DIR}/src/sim_timeout.sv
${PRJ_COMMON_VERIFICATION_DIR}/src/stream_watchdog.sv
${PRJ_COMMON_VERIFICATION_DIR}/src/signal_highlighter.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
${PRJ_TECH_CELLS_GENERIC_DIR}/src/rtl/tc_sram.sv
${PRJ_TECH_CELLS_GENERIC_DIR}/src/rtl/tc_sram_impl.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
${PRJ_TECH_CELLS_GENERIC_DIR}/src/rtl/tc_clk.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
${PRJ_TECH_CELLS_GENERIC_DIR}/src/deprecated/pulp_clock_gating_async.sv
${PRJ_TECH_CELLS_GENERIC_DIR}/src/deprecated/cluster_clk_cells.sv
${PRJ_TECH_CELLS_GENERIC_DIR}/src/deprecated/pulp_clk_cells.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+${PRJ_COMMON_CELLS_DIR}/include
${PRJ_COMMON_CELLS_DIR}/src/binary_to_gray.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+${PRJ_COMMON_CELLS_DIR}/include
${PRJ_COMMON_CELLS_DIR}/src/cb_filter_pkg.sv
${PRJ_COMMON_CELLS_DIR}/src/cc_onehot.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_reset_ctrlr_pkg.sv
${PRJ_COMMON_CELLS_DIR}/src/cf_math_pkg.sv
${PRJ_COMMON_CELLS_DIR}/src/clk_int_div.sv
${PRJ_COMMON_CELLS_DIR}/src/credit_counter.sv
${PRJ_COMMON_CELLS_DIR}/src/delta_counter.sv
${PRJ_COMMON_CELLS_DIR}/src/ecc_pkg.sv
${PRJ_COMMON_CELLS_DIR}/src/edge_propagator_tx.sv
${PRJ_COMMON_CELLS_DIR}/src/exp_backoff.sv
${PRJ_COMMON_CELLS_DIR}/src/fifo_v3.sv
${PRJ_COMMON_CELLS_DIR}/src/gray_to_binary.sv
${PRJ_COMMON_CELLS_DIR}/src/heaviside.sv
${PRJ_COMMON_CELLS_DIR}/src/isochronous_4phase_handshake.sv
${PRJ_COMMON_CELLS_DIR}/src/isochronous_spill_register.sv
${PRJ_COMMON_CELLS_DIR}/src/lfsr.sv
${PRJ_COMMON_CELLS_DIR}/src/lfsr_16bit.sv
${PRJ_COMMON_CELLS_DIR}/src/lfsr_8bit.sv
${PRJ_COMMON_CELLS_DIR}/src/lossy_valid_to_stream.sv
${PRJ_COMMON_CELLS_DIR}/src/mv_filter.sv
${PRJ_COMMON_CELLS_DIR}/src/onehot_to_bin.sv
${PRJ_COMMON_CELLS_DIR}/src/plru_tree.sv
${PRJ_COMMON_CELLS_DIR}/src/passthrough_stream_fifo.sv
${PRJ_COMMON_CELLS_DIR}/src/popcount.sv
${PRJ_COMMON_CELLS_DIR}/src/ring_buffer.sv
${PRJ_COMMON_CELLS_DIR}/src/rr_arb_tree.sv
${PRJ_COMMON_CELLS_DIR}/src/rstgen_bypass.sv
${PRJ_COMMON_CELLS_DIR}/src/serial_deglitch.sv
${PRJ_COMMON_CELLS_DIR}/src/shift_reg.sv
${PRJ_COMMON_CELLS_DIR}/src/shift_reg_gated.sv
${PRJ_COMMON_CELLS_DIR}/src/spill_register_flushable.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_demux.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_filter.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_fork.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_intf.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_join_dynamic.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_mux.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_throttle.sv
${PRJ_COMMON_CELLS_DIR}/src/sub_per_hash.sv
${PRJ_COMMON_CELLS_DIR}/src/sync.sv
${PRJ_COMMON_CELLS_DIR}/src/sync_wedge.sv
${PRJ_COMMON_CELLS_DIR}/src/unread.sv
${PRJ_COMMON_CELLS_DIR}/src/read.sv
${PRJ_COMMON_CELLS_DIR}/src/addr_decode_dync.sv
${PRJ_COMMON_CELLS_DIR}/src/boxcar.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_2phase.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_4phase.sv
${PRJ_COMMON_CELLS_DIR}/src/clk_int_div_static.sv
${PRJ_COMMON_CELLS_DIR}/src/trip_counter.sv
${PRJ_COMMON_CELLS_DIR}/src/addr_decode.sv
${PRJ_COMMON_CELLS_DIR}/src/addr_decode_napot.sv
${PRJ_COMMON_CELLS_DIR}/src/multiaddr_decode.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+${PRJ_COMMON_CELLS_DIR}/include
${PRJ_COMMON_CELLS_DIR}/src/cb_filter.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_fifo_2phase.sv
${PRJ_COMMON_CELLS_DIR}/src/clk_mux_glitch_free.sv
${PRJ_COMMON_CELLS_DIR}/src/counter.sv
${PRJ_COMMON_CELLS_DIR}/src/ecc_decode.sv
${PRJ_COMMON_CELLS_DIR}/src/ecc_encode.sv
${PRJ_COMMON_CELLS_DIR}/src/edge_detect.sv
${PRJ_COMMON_CELLS_DIR}/src/lzc.sv
${PRJ_COMMON_CELLS_DIR}/src/max_counter.sv
${PRJ_COMMON_CELLS_DIR}/src/rstgen.sv
${PRJ_COMMON_CELLS_DIR}/src/spill_register.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_delay.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_fifo.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_fork_dynamic.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_join.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_reset_ctrlr.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_fifo_gray.sv
${PRJ_COMMON_CELLS_DIR}/src/fall_through_register.sv
${PRJ_COMMON_CELLS_DIR}/src/id_queue.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_to_mem.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_arbiter_flushable.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_fifo_optimal_wrap.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_register.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_xbar.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_fifo_gray_clearable.sv
${PRJ_COMMON_CELLS_DIR}/src/cdc_2phase_clearable.sv
${PRJ_COMMON_CELLS_DIR}/src/mem_to_banks_detailed.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_arbiter.sv
${PRJ_COMMON_CELLS_DIR}/src/stream_omega_net.sv
${PRJ_COMMON_CELLS_DIR}/src/mem_to_banks.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+${PRJ_COMMON_CELLS_DIR}/include
${PRJ_COMMON_CELLS_DIR}/test/cdc_2phase_synth.sv
${PRJ_COMMON_CELLS_DIR}/test/id_queue_synth.sv
${PRJ_COMMON_CELLS_DIR}/test/stream_arbiter_synth.sv
${PRJ_COMMON_CELLS_DIR}/test/ecc_synth.sv
${PRJ_COMMON_CELLS_DIR}/test/synth_bench.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+${PRJ_COMMON_CELLS_DIR}/include
${PRJ_COMMON_CELLS_DIR}/src/deprecated/clock_divider_counter.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/clk_div.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/find_first_one.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/generic_LFSR_8bit.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/generic_fifo.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/prioarbiter.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/pulp_sync.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/pulp_sync_wedge.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/rrarbiter.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/clock_divider.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/fifo_v2.sv
${PRJ_COMMON_CELLS_DIR}/src/deprecated/fifo_v1.sv
${PRJ_COMMON_CELLS_DIR}/src/edge_propagator_ack.sv
${PRJ_COMMON_CELLS_DIR}/src/edge_propagator.sv
${PRJ_COMMON_CELLS_DIR}/src/edge_propagator_rx.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+${PRJ_COMMON_CELLS_DIR}/include
+incdir+${PRJ_AXI_DIR}/include
${PRJ_AXI_DIR}/src/axi_pkg.sv
${PRJ_AXI_DIR}/src/axi_demux_id_counters.sv
${PRJ_AXI_DIR}/src/axi_intf.sv
${PRJ_AXI_DIR}/src/axi_atop_filter.sv
${PRJ_AXI_DIR}/src/axi_burst_splitter_gran.sv
${PRJ_AXI_DIR}/src/axi_burst_unwrap.sv
${PRJ_AXI_DIR}/src/axi_bus_compare.sv
${PRJ_AXI_DIR}/src/axi_cdc_dst.sv
${PRJ_AXI_DIR}/src/axi_cdc_src.sv
${PRJ_AXI_DIR}/src/axi_cut.sv
${PRJ_AXI_DIR}/src/axi_delayer.sv
${PRJ_AXI_DIR}/src/axi_demux_simple.sv
${PRJ_AXI_DIR}/src/axi_dw_downsizer.sv
${PRJ_AXI_DIR}/src/axi_dw_upsizer.sv
${PRJ_AXI_DIR}/src/axi_fifo.sv
${PRJ_AXI_DIR}/src/axi_fifo_delay_dyn.sv
${PRJ_AXI_DIR}/src/axi_id_remap.sv
${PRJ_AXI_DIR}/src/axi_id_prepend.sv
${PRJ_AXI_DIR}/src/axi_inval_filter.sv
${PRJ_AXI_DIR}/src/axi_isolate.sv
${PRJ_AXI_DIR}/src/axi_join.sv
${PRJ_AXI_DIR}/src/axi_lite_demux.sv
${PRJ_AXI_DIR}/src/axi_lite_dw_converter.sv
${PRJ_AXI_DIR}/src/axi_lite_from_mem.sv
${PRJ_AXI_DIR}/src/axi_lite_join.sv
${PRJ_AXI_DIR}/src/axi_lite_lfsr.sv
${PRJ_AXI_DIR}/src/axi_lite_mailbox.sv
${PRJ_AXI_DIR}/src/axi_lite_mux.sv
${PRJ_AXI_DIR}/src/axi_lite_regs.sv
${PRJ_AXI_DIR}/src/axi_lite_to_apb.sv
${PRJ_AXI_DIR}/src/axi_lite_to_axi.sv
${PRJ_AXI_DIR}/src/axi_modify_address.sv
${PRJ_AXI_DIR}/src/axi_mux.sv
${PRJ_AXI_DIR}/src/axi_rw_join.sv
${PRJ_AXI_DIR}/src/axi_rw_split.sv
${PRJ_AXI_DIR}/src/axi_serializer.sv
${PRJ_AXI_DIR}/src/axi_slave_compare.sv
${PRJ_AXI_DIR}/src/axi_throttle.sv
${PRJ_AXI_DIR}/src/axi_to_detailed_mem.sv
${PRJ_AXI_DIR}/src/axi_burst_splitter.sv
${PRJ_AXI_DIR}/src/axi_cdc.sv
${PRJ_AXI_DIR}/src/axi_demux.sv
${PRJ_AXI_DIR}/src/axi_err_slv.sv
${PRJ_AXI_DIR}/src/axi_dw_converter.sv
${PRJ_AXI_DIR}/src/axi_from_mem.sv
${PRJ_AXI_DIR}/src/axi_id_serialize.sv
${PRJ_AXI_DIR}/src/axi_lfsr.sv
${PRJ_AXI_DIR}/src/axi_multicut.sv
${PRJ_AXI_DIR}/src/axi_to_axi_lite.sv
${PRJ_AXI_DIR}/src/axi_to_mem.sv
${PRJ_AXI_DIR}/src/axi_zero_mem.sv
${PRJ_AXI_DIR}/src/axi_interleaved_xbar.sv
${PRJ_AXI_DIR}/src/axi_iw_converter.sv
${PRJ_AXI_DIR}/src/axi_lite_xbar.sv
${PRJ_AXI_DIR}/src/axi_xbar_unmuxed.sv
${PRJ_AXI_DIR}/src/axi_to_mem_banked.sv
${PRJ_AXI_DIR}/src/axi_to_mem_interleaved.sv
${PRJ_AXI_DIR}/src/axi_to_mem_split.sv
${PRJ_AXI_DIR}/src/axi_xbar.sv
${PRJ_AXI_DIR}/src/axi_xp.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+${PRJ_COMMON_CELLS_DIR}/include
+incdir+${PRJ_AXI_DIR}/include
${PRJ_AXI_DIR}/test/axi_synth_bench.sv

